spring.application.name=user-management-service

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/user_management_db
spring.datasource.username=root
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8085

# JWT Configuration
jwt.secret=Your_key
jwt.expiration=86400000